### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by jonathansel** [xhwdlgy5201/SuperThermal-thermal-matching#1]
Hello, 

Thank you for sharing your implementation. I am having some trouble running `python batch_draw_matching_points.py --resume KAIST.pth.tar --folder test_input`

The resulting error is as followed while using pytorch 2.01: 

`Loading model from KAIST.pth.tar
['test_input/II01985.jpg', 'test_input/II01980.jpg']
Image 1 path: test_input/II01980.jpg
Image 2 path: test_input/II01985.jpg
/home/jonathansel/SuperThermal-thermal-matching/model/thermal_det_module.py:197: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  psf = im1w_score.new_tensor(
Traceback (most recent call last):
  File "batch_draw_matching_points.py", line 95, in <module>
    kp1, des1, img1 = model.detectAndCompute(img1_path, device, (240, 320))
  File "/home/jonathansel/SuperThermal-thermal-matching/model/thermal_net_so.py", line 205, in detectAndCompute
    _, kp, des = self.inference(img, img_info, img_raw)
  File "/home/jonathansel/SuperThermal-thermal-matching/model/thermal_net_so.py", line 154, in inference
    im_score = self.det.process(im_rawsc)[0]
  File "/home/jonathansel/SuperThermal-thermal-matching/model/thermal_det_module.py", line 202, in process
    im1w_score = F.conv2d(
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
`

![image](https://github.com/xhwdlgy5201/SuperThermal-thermal-matching/assets/32660117/30246f41-12c0-4947-a4c0-0fd29ccee5ea)

If you have any suggestions on how to fix please let me know, thank you!

**Comment by ElHouas** [comment]
Hey @jonathansel,

I am facing the same problem. Have you been able to solve it?
